#!/usr/bin/python3
from dreamtown_config import *
import sys
import binascii
import os
import json
import sqlite3
import hashlib

print("Content-Type: application/json")
print("")
method = os.environ["REQUEST_METHOD"]
if method != "POST":
	print("Expected POST")
	os._exit()
	

content_len = int(os.environ["CONTENT_LENGTH"])
post = sys.stdin.read(content_len)
jsonData = json.loads(post)
result = {"status":SUCCESS}
	
def TryRemove():
	ItemId = jsonData['itemId']
	Quantity = jsonData['quantity']
	authToken = jsonData['authToken']
	
	c = db.cursor()
	cur = c.execute('SELECT COUNT(1) from users WHERE LastSession=?',(authToken,))
	rows = cur.fetchone()
	count = rows[0]
	if count == 0:
		result['status'] = USER_DOES_NOT_EXIST
		return 0
	
	#Find Username
	cur = c.execute('SELECT Name from users WHERE LastSession=?',(authToken,))
	rows = cur.fetchone()
	username = rows[0]
		
	cur = c.execute('SELECT Quantity from itemList WHERE Name=? and ItemId=?',(username,ItemId))
	rows = cur.fetchone()
	curQuantity = rows[0]
	if curQuantity - Quantity > 0:
		c.execute('UPDATE itemList SET Quantity=Quantity-? WHERE Name=? and ItemId=?',(Quantity,username,ItemId))
		return 0
	else:
		c.execute('DELETE from itemList WHERE Name=? and ItemId=?',(username,ItemId))
		return 0


try: 
	db = sqlite3.connect(SQLLITE_DB_PATH)
	TryRemove()
	db.commit()
	db.close()
except Exception as e:
	print(e)
	os._exit()

print(json.dumps(result))