#!/usr/bin/python3
from dreamtown_config import *
import sys
import binascii
import os
import json
import sqlite3
import time
import hashlib

print("Content-Type: application/json")
print("")
method = os.environ["REQUEST_METHOD"]
if method != "POST":
	print("Expected POST")
	os._exit(1)
	

content_len = int(os.environ["CONTENT_LENGTH"])
post = sys.stdin.read(content_len)
jsonData = json.loads(post)
result = {"status":SUCCESS}
	
def TryGet():
	authToken = jsonData['authToken']
	
	c = db.cursor()
	c.execute('SELECT COUNT(1) from users WHERE LastSession=?',(authToken,))
	rows = c.fetchone()
	count = rows[0]
	if count == 0:
		result['status'] = USER_DOES_NOT_EXIST
		return 0
	
	#Find Username
	c.execute('SELECT Name from users WHERE LastSession=?',(authToken,))
	rows = c.fetchone()
	username = rows[0]
	
	c.execute('SELECT ActualCharacterId from characterList WHERE Name=? AND ActualCharacterId IS NOT NULL',(username,))
	rows = c.fetchone()
	ActualCharacterId = rows[0]
		
	c.execute('SELECT CharacterId from characterList WHERE Name=?',(username,))
	rows = c.fetchall()
	characterIds = []
	for row in rows:
		if row[0] != None and row[0] != "":
			characterIds.append(row[0])
	
	result['actualCharacterId'] = ActualCharacterId
	result['characterIds'] = characterIds
	


try: 
	db = DbConnect()
	TryGet()
	db.commit()
	db.close()
except Exception as e:
	raise e
	os._exit(1)

print(json.dumps(result))