#!/usr/bin/python3
from dreamtown_config import *
import sys
import binascii
import os
import json
import sqlite3
import hashlib

print("Content-Type: application/json")
print("")
method = os.environ["REQUEST_METHOD"]
if method != "POST":
	print("Expected POST")
	os._exit(1)
	

content_len = int(os.environ["CONTENT_LENGTH"])
post = sys.stdin.read(content_len)
jsonData = json.loads(post)
result = {"status":SUCCESS}
	
def TrySwitch():
	CharacterId = jsonData['characterId']
	authToken = jsonData['authToken']
	
	c = db.cursor()
	c.execute('SELECT COUNT(1) from users WHERE LastSession=?',(authToken,))
	rows = c.fetchone()
	count = rows[0]
	if count == 0:
		result['status'] = USER_DOES_NOT_EXIST
		return 0
	
	#Find Username
	c.execute('SELECT Name from users WHERE LastSession=?',(authToken,))
	rows = c.fetchone()
	username = rows[0]
		
	c.execute('UPDATE characterList SET ActualCharacterId=? WHERE Name=? and ActualCharacterId IS NOT NULL',(CharacterId,username))


try: 
	db = DbConnect()
	TrySwitch()
	db.commit()
	db.close()
except Exception as e:
	raise e
	os._exit(1)

#print(json.dumps(result))
#For some reason, on this request only responding '{"status":1}' or any JSON with a string as a key, Crashes paper mario (erh dream town)
print("") #print nothing instead.. temporary fix (tho the client never uses the status code to check anything .. it still does assign it to a variable)